name: MCP Docs Server - Release Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version for this release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
          token: ${{ secrets.PAT_GITHUB }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Reset local changes
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fdx

      - name: Configure git user
        run: |
          git config user.name "Dariel Noel"
          git config user.email "darielnoel@gmail.com"

      - name: Install dependencies
        run: npx @tiberriver256/docs-to-mcp-cli --docs 'docs/**/*.md' --packageName 'kaibanjs-mcp-docs-server' --outDir .mcp-docs-server

      - name: Display changes
        run: |
          echo "Showing status..."
          git status
          echo "Showing diff..."
          git diff

      - name: Update package.json version
        run: |
          cd .mcp-docs-server
          npm version ${{ github.event.inputs.version }}

      - name: Update package.json name
        run: |
          cd .mcp-docs-server
          npm pkg set name="@kaibanjs/mcp-docs-server"

      - name: Push changes and tags
        run: |
          git push origin main
          git tag -a "mcp-docs-server-v${{ github.event.inputs.version }}" -m "Release version ${{ github.event.inputs.version }} for kaibanjs-mcp-docs-server"
          git push origin "mcp-docs-server-v${{ github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Publish to npm
        run: |
          cd .mcp-docs-server
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
